version: '3'

services:
    wolt-app:
        container_name: wolt-app
        image: wolt-app
        stdin_open: true
        tty: true
        build: .
        command: python3 -m wolt.app
        env_file:
          - .env
        ports:
            - "5002:5000"
        volumes:
            - .:/code
